name: Generate F-Droid Repo

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-fdroid-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fdroidserver jq

      - name: Download latest release APK
        id: download_apk
        run: |
          release_url="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest"
          assets=$(curl -s $release_url | jq -r '.assets[] | select(.name | endswith(".apk")) | .browser_download_url')
          mkdir -p temp-apk
          for url in $assets; do
            wget -O "temp-apk/$(basename $url)" "$url"
          done

      - name: Prepare F-Droid repo
        run: |
          mkdir -p fdroid
          cd fdroid
          fdroid init
          cp ../temp-apk/*.apk ./repo/
          fdroid update --create-metadata --pretty

      - name: Upload repo as artifact
        uses: actions/upload-artifact@v4
        with:
          name: fdroid-repo
          path: fdroid/

      - name: Deploy to GitHub Pages
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./fdroid
